---
params:
  update_date: FALSE
  run_chunk: FALSE
date: "`r source('_supp/helper.R'); newdate_func(params$update_date)`"
title: "`r totitle('Quá trình ngẫu nhiên trong phân tích sống sót phi tham số')`"
output: 
  bookdown::html_document2:
    code_folding: hide
    number_sections: true
bibliography: ["_supp/citation.bib"]
link-citations: true
---

\newcommand{\bf}[1]{\boldsymbol{#1}}
\newcommand{\hat}[1]{\widehat{#1}}
\newcommand{\mm}[1]{\mathbb{#1}}
\newcommand{\bar}[1]{\overline{#1}}
\newcommand{\tp}[1]{{#1}^{\top}}

\def\E{\Bbb{E}}
\def\V{\Bbb{V}}
\def\P{\Bbb{P}}
\def\I{{\large\unicode{x1D7D9}}}
\def\indep{\perp\!\!\!\!\perp}
\newcommand{\overeq}[2]{\stackrel{#1}{#2}}
\def\epsilon{\varepsilon} 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
ttt = purrr::partial(totitle, icon = "")
```

::: {.watermark}
*DRAFT*
:::

::: {.right .shad}
[Tham khảo tại chương 3, @aal2008]
:::

---

# `r ttt('ước lượng của Nelson-Aalen')`

Ta cần nhắc lại một số khái niệm và ký hiệu sẽ được sử dụng trong phần này. Ta có $N_i(t)$ là số sự kiện xày ra của bệnh nhân $i$ trong khoảng thời gian $[0,t]$. Cường độ của $N_i(t)$ là $\lambda_i(t) = \alpha(t)Y_i(t)$ với $\alpha(t)$ là một hàm số không âm, $Y_i(t)$ là hàm chỉ tiêu bằng 1 nếu bệnh nhân $i$th còn sống ngay trước thời điểm $t$, và bằng 0 nếu đã được ghi nhận tử vong. Ta xem xét $N(t) = \sum_{i=1}^nN_i(t)$ là tổng số sự kiện xảy ra tinh tới thời điểm $t$. và ta có
$$
\lambda(t) = \sum_{i=1}^n\lambda_i(t) = \alpha(t)Y(t),
(\#eq:eq2)
$$
với $Y(t) = \sum_{i=1}^nY_i(t)$ là số bệnh nhân còn sống ngay trước thời điểm $t$.

## `r ttt('tập dữ liệu sống sót')`

Đối với dạng dữ liệu về sống sót thì mục tiêu của ta là xem xét thời gian xảy ra một sự kiện nào đó của những cá nhân trong một quần thể. Gọi $\alpha(t)$ là tốc độ nguy hiểm tức thời, ta sẽ có $\alpha(t)dt$ là xác suất mà sự kiện sẽ xảy ra trong khoảng thời gian $[t,t+dt)$ biết rằng nó chưa xảy ra trước đó. 






















<!-- ----------------------------------------------------------------------------- -->

::: {.shad}
# _References_ {-}
:::
