---
params:
  update_date: FALSE
  run_chunk: FALSE
date: "`r source('_supp/helper.R'); newdate_func(params$update_date)`"
title: "`r totitle('Quá trình ngẫu nhiên trong phân tích sống sót phi tham số')`"
output: 
  bookdown::html_document2:
    code_folding: hide
    number_sections: true
bibliography: ["_supp/citation.bib"]
link-citations: true
---

\newcommand{\bf}[1]{\boldsymbol{#1}}
\newcommand{\hat}[1]{\widehat{#1}}
\newcommand{\mm}[1]{\mathbb{#1}}
\newcommand{\bar}[1]{\overline{#1}}
\newcommand{\tp}[1]{{#1}^{\top}}

\def\E{\Bbb{E}}
\def\V{\Bbb{V}}
\def\P{\Bbb{P}}
\def\I{{\large\unicode{x1D7D9}}}
\def\indep{\perp\!\!\!\!\perp}
\newcommand{\overeq}[2]{\stackrel{#1}{#2}}
\def\epsilon{\varepsilon} 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
totitle = purrr::partial(totitle, icon = "")
```

::: {.watermark}
*DRAFT*
:::

::: {.right .shad}
[Tham khảo tại chương 3, @aal2008]
:::

---

```{r fig1, fig.align='center', fig.cap="*Dữ liệu thời gian tử vong của các bệnh nhân trong một nghiên cứu.*", eval=params$run_chunk}
time_range = 1:15
library(tidyverse)
set.seed(222)
d1 = dplyr::tibble(people = paste("người",c(paste0("0",1:9),paste0(10:20)) ) , 
                   time = sample(time_range, 20, replace = T),
                   status = sample(c("failure","censor"), 20, replace = TRUE, prob = c(0.7,0.3)))
draw_table(d1)
```

```{r fig2, fig.align='center', fig.cap="*Biểu đồ thể hiện số liệu tử vong của các bệnh nhân.*", eval=params$run_chunk}
d1%>%
  arrange(time)%>%
  mutate(people = factor(people, levels = d1$people[order(d1$time, decreasing = T)] ))%>%
  ggplot(aes(x = people, y = time))+ 
  geom_hline( yintercept = d1[d1$status=="failure",]$time, linetype = "solid", color = "grey90")+
  geom_hline( yintercept = d1[d1$status=="censor",]$time, color = "grey90", linetype = "dashed")+
  geom_point(mapping = aes(x = people, y = time, shape = status, color = status),cex = 2.5)+
  scale_shape_manual(values=c(1,19))+
  geom_segment(aes(x = people,xend = people, y = 0, yend = time,color = status))+
  coord_flip()+
  scale_y_continuous(breaks= time_range)+
  theme_classic()
```
















<!-- ----------------------------------------------------------------------------- -->

::: {.shad}
# _References_ {-}
:::
